name: Cloud Security Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scanner
        run: python -m cli.main
